Lourdes/squarelotron
MinionsGroup/devfund-f pull request #30
Opened 2018-05-02 04:52 UTC by lourdesVillca

2018-05-02 04:55 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/Squarelotron.java
> +    private int[][] squarelotron;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Rename field "squarelotron" [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1700)

2018-05-02 04:55 UTC, carledriss commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2018-05-03 02:30 UTC, lourdesVillca commented
![progress2](https://user-images.githubusercontent.com/19194892/39557819-605be5e6-4e58-11e8-8895-b006a9dbee4c.png)

2018-05-03 15:36 UTC, carledriss commented
@lourdesVillca 
Increase the code coverage.
https://codecov.io/gh/Minions-F/devfund/pull/30/diff?src=pr&el=tree#diff-c3JjL21haW4vamF2YS9vcmcvbWluaW9ucy9kZXZmdW5kL2xvdXJkZXMvU3F1YXJlbG90cm9uLmphdmE=

It is missing unit tests when rotate is sending numberOfTurns negative

2018-05-03 15:37 UTC, carledriss requested changes
See the observations

2018-05-06 22:55 UTC, carledriss approved these changes

2018-05-06 23:05 UTC, merged