Mauricio z/whackamole
MinionsGroup/devfund-f pull request #33
Opened 2018-05-02 20:32 UTC by mauricioZelaya

uploading final version of squarelotron homework

2018-05-02 20:35 UTC, carledriss commented on src/main/java/org/minions/devfund/mauricioz/Squarelotron.java
> +    private int[][] squarelotron;
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Rename field "squarelotron" [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1700)

2018-05-02 20:35 UTC, carledriss commented
SonarQube analysis reported 1 issue
* ![MAJOR][MAJOR] 1 major

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

2018-05-02 23:27 UTC, mauricioZelaya commented
![image](https://user-images.githubusercontent.com/28932391/39554075-cf386bac-4e3e-11e8-8f6d-269087a2d28f.png)
![image](https://user-images.githubusercontent.com/28932391/39554082-d37659b8-4e3e-11e8-9d68-2767ac429e20.png)

2018-05-03 15:48 UTC, carledriss requested changes
@mauricioZelaya 
Please update against develop

2018-05-03 23:10 UTC, closed without merging