Lourdes/battleship
MinionsGroup/devfund-f pull request #59
Opened 2018-05-24 19:00 UTC by lourdesVillca

2018-05-24 19:01 UTC, lourdesVillca commented
![image](https://user-images.githubusercontent.com/19194892/40505775-50778d44-5f63-11e8-867e-5b09f15b2288.png)

2018-05-24 19:02 UTC, carledriss commented on src/test/java/org/minions/devfund/lourdes/battleship/OceanTest.java
> +        Ocean ocean = new Ocean();
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') Rename "ocean" which hides the field declared at line 13. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AHiddenFieldCheck)

2018-05-24 19:02 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ship.java
> +                } else if (ocean.isOccupied(row + i, column)) {
![MAJOR](https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR') This branch's code block is the same as the block for the branch on line 117. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1871)

2018-05-24 19:02 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +        SHIP_TYPE.forEach((key, value) -> {
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Remove useless curly braces around statement [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1602)

2018-05-24 19:02 UTC, carledriss commented
SonarQube analysis reported 3 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-06-14 21:17 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +                    System.out.print(" " + ships[i][j] + " ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-06-14 21:17 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +            System.out.println("");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-06-14 21:17 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +        System.out.println("");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-06-14 21:17 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +        System.out.print(arrayPosition);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-06-14 21:17 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +            System.out.println("");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-06-14 21:17 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +            System.out.print(i);
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-06-14 21:17 UTC, carledriss commented on src/main/java/org/minions/devfund/lourdes/battleship/Ocean.java
> +                    System.out.print(" . ");
![MINOR](https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR') Replace this use of System.out or System.err by a logger. [![rule](https://sonarsource.github.io/sonar-github/rule.png)](https://sonarcloud.io/coding_rules#rule_key=squid%3AS106)

2018-06-14 21:17 UTC, carledriss commented
SonarQube analysis reported 10 issues
* ![MAJOR][MAJOR] 2 major
* ![MINOR][MINOR] 8 minor

Watch the comments in this conversation to review them.

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-06-15 03:30 UTC, carledriss commented
SonarQube analysis reported 1 issue
* ![MINOR][MINOR] 1 minor

Watch the comments in this conversation to review them.

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

2018-06-17 18:46 UTC, carledriss requested changes
Increase the code coverage

2018-06-20 00:17 UTC, carledriss approved these changes

2018-06-20 00:17 UTC, merged